package bean;
// Generated 28/05/2016 15:07:15 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer clicod;
     private String clinome;
     private Date clinasc;
     private int clirg;
     private int clicpf;
     private String clisangue;

    public Cliente() {
    }

    public Cliente(String clinome, Date clinasc, int clirg, int clicpf, String clisangue) {
       this.clinome = clinome;
       this.clinasc = clinasc;
       this.clirg = clirg;
       this.clicpf = clicpf;
       this.clisangue = clisangue;
    }
   
    public Integer getClicod() {
        return this.clicod;
    }
    
    public void setClicod(Integer clicod) {
        this.clicod = clicod;
    }
    public String getClinome() {
        return this.clinome;
    }
    
    public void setClinome(String clinome) {
        this.clinome = clinome;
    }
    public Date getClinasc() {
        return this.clinasc;
    }
    
    public void setClinasc(Date clinasc) {
        this.clinasc = clinasc;
    }
    public int getClirg() {
        return this.clirg;
    }
    
    public void setClirg(int clirg) {
        this.clirg = clirg;
    }
    public int getClicpf() {
        return this.clicpf;
    }
    
    public void setClicpf(int clicpf) {
        this.clicpf = clicpf;
    }
    public String getClisangue() {
        return this.clisangue;
    }
    
    public void setClisangue(String clisangue) {
        this.clisangue = clisangue;
    }




}


