package model.beans;
// Generated 09/11/2015 08:22:27 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer clicod;
     private String clinome;
     private Integer clirg;
     private Set dependenteses = new HashSet(0);

    public Cliente() {
    }

    public Cliente(String clinome, Integer clirg, Set dependenteses) {
       this.clinome = clinome;
       this.clirg = clirg;
       this.dependenteses = dependenteses;
    }
   
    public Integer getClicod() {
        return this.clicod;
    }
    
    public void setClicod(Integer clicod) {
        this.clicod = clicod;
    }
    public String getClinome() {
        return this.clinome;
    }
    
    public void setClinome(String clinome) {
        this.clinome = clinome;
    }
    public Integer getClirg() {
        return this.clirg;
    }
    
    public void setClirg(Integer clirg) {
        this.clirg = clirg;
    }
    public Set getDependenteses() {
        return this.dependenteses;
    }
    
    public void setDependenteses(Set dependenteses) {
        this.dependenteses = dependenteses;
    }




}


