package model.beans;
// Generated 09/11/2015 08:22:27 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Dependentes generated by hbm2java
 */
public class Dependentes  implements java.io.Serializable {


     private Integer depcod;
     private Cliente cliente;
     private String depnome;
     private Integer depcpf;
     private Integer deprg;
     private String depfone;
     private Date datanasc;
     private Date datainclusao;
     private String depsexo;
     private Set enderecos = new HashSet(0);

    public Dependentes() {
    }

	
    public Dependentes(Cliente cliente) {
        this.cliente = cliente;
    }
    public Dependentes(Cliente cliente, String depnome, Integer depcpf, Integer deprg, String depfone, Date datanasc, Date datainclusao, String depsexo, Set enderecos) {
       this.cliente = cliente;
       this.depnome = depnome;
       this.depcpf = depcpf;
       this.deprg = deprg;
       this.depfone = depfone;
       this.datanasc = datanasc;
       this.datainclusao = datainclusao;
       this.depsexo = depsexo;
       this.enderecos = enderecos;
    }
   
    public Integer getDepcod() {
        return this.depcod;
    }
    
    public void setDepcod(Integer depcod) {
        this.depcod = depcod;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getDepnome() {
        return this.depnome;
    }
    
    public void setDepnome(String depnome) {
        this.depnome = depnome;
    }
    public Integer getDepcpf() {
        return this.depcpf;
    }
    
    public void setDepcpf(Integer depcpf) {
        this.depcpf = depcpf;
    }
    public Integer getDeprg() {
        return this.deprg;
    }
    
    public void setDeprg(Integer deprg) {
        this.deprg = deprg;
    }
    public String getDepfone() {
        return this.depfone;
    }
    
    public void setDepfone(String depfone) {
        this.depfone = depfone;
    }
    public Date getDatanasc() {
        return this.datanasc;
    }
    
    public void setDatanasc(Date datanasc) {
        this.datanasc = datanasc;
    }
    public Date getDatainclusao() {
        return this.datainclusao;
    }
    
    public void setDatainclusao(Date datainclusao) {
        this.datainclusao = datainclusao;
    }
    public String getDepsexo() {
        return this.depsexo;
    }
    
    public void setDepsexo(String depsexo) {
        this.depsexo = depsexo;
    }
    public Set getEnderecos() {
        return this.enderecos;
    }
    
    public void setEnderecos(Set enderecos) {
        this.enderecos = enderecos;
    }




}


